POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJ1bmEiLCJpZCI6IjY5OWRlMmZhODJlZDJhN2JlYWJiMzVlYSIsImlhdCI6MTc3MTk1NDk0Nn0.Mbrh3h551yg3w-KzIXTYgPug21p-_Andzk8Z0RuIXpQ

{
  "title": "How to become the best thief that ever was",
  "author": "Runa Cubix",
  "url": "www.some/url.com",
  "likes": "204"
}